version: '3.8'

services:
  graph-db:
    build:
      context: ..
      dockerfile: Graph_Database_Service/Dockerfile
    container_name: cse-explorer-graph-db
    ports:
      - "7474:7474"  # Neo4j HTTP (browser access)
      - "7687:7687"  # Neo4j Bolt (database connections)
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*,apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  cse-explorer-network:
    driver: bridge