name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('tests/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r tests/requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v --tb=short
    
    - name: Test Report
      if: always()
      run: |
        echo "========================================="
        echo "Test Suite Completed"
        echo "========================================="
        echo ""
        echo "Tests validate:"
        echo "✓ JWT token creation patterns"
        echo "✓ Password hashing security"
        echo "✓ Kafka message publishing"
        echo "✓ Redis pub/sub messaging"
        echo "✓ Singleton pattern implementation"
        echo "✓ Message processor initialization"
        echo "✓ Chat history storage"
        echo ""
        echo "Check the test output above for details."